camera:
  exposure: 50000  # in micro-seconds
  gain: 10
  width: 600
  height: 600
  xcenter: 204
  ycenter: 204

daq:
  frequencyw1: 0.5
  amplitudew1: 0.1
  frequencyw2: 10
  amplitudew2: 5

data:
  min_cycles: 6
  filename: Sprayed_ITO
  total_frames: 500